version: 2
jobs:
  build:
    docker:
      - image: syuo7/circleci_test
    steps:
      - checkout
      - run: pwd
      - run: ls -al
      - run: ./mkunxarc.sh
      - run: cd unix
      - run: make -f Makefile.gtk
      - run: ls -al
